services:
  greenmail:
    image: greenmail/standalone:2.0.0
    environment:
      - JAVA_OPTS=-Dgreenmail.verbose
    ports:
      - 3025:3025 # SMTP
      - 3143:3143 # IMAP
      - 8080:8080 # API

  php-fpm:
    build:
      context: php-fpm

  nginx:
    build:
      context: nginx
    depends_on:
      - greenmail
      - php-fpm
    ports:
      - 8090:8080
